### ISSUE TITLE
The Front Controller "getContext" method don't work after cache

### ISSUE THREAD

**Issue by Foine** [novius-os/core#102]
Hello !

I found that the "getContext" method do not work if you use it after the cache.
But if you use 

```
\Nos\Nos::main_controller->getPage()->context
```

It works perfectly.
I don't know what is the better method to prevent this issue.
Fallback on the second method when you call the first after the cache or fill the "_context" properties of the front controller even after the cache.

**Comment by felixgilles** [comment]
Fixed by ac09cb17f89f5a73fc05e7ce802b3c66ad30e089
Thank
