### ISSUE TITLE
The last version made some buggy url for urlEnhancer on a page

### ISSUE THREAD

**Issue by Foine** [novius-os/core#18]
Hello,
I think the commit 6706518241adb100068e3c28985c7149e89d63fd ("Bugfix for Tools_Url::page() returning path version of URL without .html") is responsible of one problem that doesn't appear before.
An example is more powerful than a long speach so : 
in this page : http://oppoc.fr/blog.html , urls for the posts are not good. In the other page of the site, they are working properly (the url() method is call everywhere).

I hope you will find a solution for this problem.

**Comment by felixgilles** [comment]
Thank Foine

A small fix can cause a big issue.

It's solved, you can update your Novius OS
