### ISSUE TITLE
Default preview for enhancers

### ISSUE THREAD

**Issue by jay3** [novius-os/core#7]
Would it be possible to add a default preview to the enhancers? For example, it could use a title and an image provided by the config file.
This could save time to create simple enhancers.

Thanks
Jay

**Comment by felixgilles** [comment]
Hi Jay,  

It's done in the 0.2 version. If an enhancer has not  specified a preview in metadata, a default preview is came with the application's icon and enhancer's name.

Thanks for this suggestion.
