### ISSUE TITLE
Bad detection of script for the addJavascriptInline method

### ISSUE THREAD

**Issue by Foine** [novius-os/core#95]
Hello.
When you use the "addJavascriptInline" method, the core test if the string starts with '&lt;script '. But, for example, twitter give us this code fore tweet button : 
    &lt;script&gt;!function(d,s,id)...

So the script node is not detected.
Does the "addJavascriptInline" method should not test if the string starts with '&lt;script' instead of '&lt;script ' ?
Thank you for your reply.

**Comment by felixgilles** [comment]
Hello Foine,

Maybe the method should test `'<script '` and `'<script>'`, I will prefer that instead of only testing '<script'

**Comment by felixgilles** [comment]
Solved by 71661f07baa57240209e1284ef1115eb41dc83d0
