### ISSUE TITLE
Enhancer previews are not displayed in the same way when update or save.

### ISSUE THREAD

**Issue by Foine** [novius-os/core#96]
Hello,

I found that enhancer previews are not displayed in the same way when you save it or when it is updated.

The difference is here : 
novius-os/static/admin/vendor/tinymce/plugins/nosenhancer/editor_plugin_src.js
line 66 and line 218
In the first case (display is updated) the html of preview is send directly.

```
enhancer.html(json.preview);
```

In the second case, for security,the preview is put in a jQuery object before and the result of the "html" method is send like this : 

```
.html($(json.preview).html());
```

But in that way, you just have the inner html of your preview.
For exemple if your preview is 

```
<div>My div</div>
```

the result of : 

```
$('<div>My div</div>').html();
```

is 

```
My div
```

And that is what append in the line 218.
To prevent that, I suggest to do : 

```
.html($(json.preview).get());
```

instead of 

```
.html($(json.preview).html());
```

I suggest to to this also in line 66 to have the same behaviour in the two case.

Thanks in advance for your answer.

**Comment by felixgilles** [comment]
Hi @Foine 

I've harmonised with e4fad67
I've passed directly the preview code to the html method in the two case

**Comment by Foine** [comment]
Seems perfect !

Thank you !
